"use client";

import { useActionState, useEffect, useState, startTransition } from "react";
import { updateIdConfig } from "@/lib/actions";
import { IdFormatConfig, formatIdPattern } from "@/lib/idGenerator";
import { toast } from "react-toastify";

interface IdFormatSettingsProps {
  initialConfig: IdFormatConfig;
}

export default function IdFormatSettings({ initialConfig }: IdFormatSettingsProps) {
  const [studentPrefix, setStudentPrefix] = useState(initialConfig.studentIdPrefix || "STU");
  const [studentYear, setStudentYear] = useState(initialConfig.studentIdYear ?? true);
  const [studentDigits, setStudentDigits] = useState(initialConfig.studentIdDigits || 4);
  const [studentFormat, setStudentFormat] = useState(
    initialConfig.studentIdFormat?.replace(/-/g, "") || "STU[YYYY][SEQ]"
  );

  const [teacherPrefix, setTeacherPrefix] = useState(initialConfig.teacherIdPrefix || "TCH");
  const [teacherYear, setTeacherYear] = useState(initialConfig.teacherIdYear ?? true);
  const [teacherDigits, setTeacherDigits] = useState(initialConfig.teacherIdDigits || 4);
  const [teacherFormat, setTeacherFormat] = useState(
    initialConfig.teacherIdFormat?.replace(/-/g, "") || "TCH[YYYY][SEQ]"
  );

  const [parentPrefix, setParentPrefix] = useState(initialConfig.parentIdPrefix || "PRN");
  const [parentDigits, setParentDigits] = useState(initialConfig.parentIdDigits || 4);
  const [parentFormat, setParentFormat] = useState(
    initialConfig.parentIdFormat?.replace(/-/g, "") || "PRN[SEQ]"
  );

  const [state, formAction] = useActionState(updateIdConfig, {
    success: false,
    error: false,
    message: "",
  });

  useEffect(() => {
    if (state.success) {
      toast.success("System ID formats updated successfully!");
    } else if (state.error && state.message) {
      toast.error(state.message);
    }
  }, [state]);

  const studentPreview = formatIdPattern(
    studentFormat,
    studentPrefix,
    studentYear,
    studentDigits,
    1
  );

  const teacherPreview = formatIdPattern(
    teacherFormat,
    teacherPrefix,
    teacherYear,
    teacherDigits,
    1
  );

  const parentPreview = formatIdPattern(parentFormat, parentPrefix, false, parentDigits, 1);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    startTransition(() => {
      formAction({
        studentIdPrefix: studentPrefix,
        studentIdYear: studentYear,
        studentIdDigits: Number(studentDigits),
        studentIdFormat: studentFormat,

        teacherIdPrefix: teacherPrefix,
        teacherIdYear: teacherYear,
        teacherIdDigits: Number(teacherDigits),
        teacherIdFormat: teacherFormat,

        parentIdPrefix: parentPrefix,
        parentIdDigits: Number(parentDigits),
        parentIdFormat: parentFormat,
      });
    });
  };

  return (
    <div className="flex flex-col gap-6 rounded-2xl border border-gray-100 bg-white p-6 shadow-sm">
      <div>
        <div className="flex items-center gap-2">
          <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-100 text-xs font-bold text-blue-700">
            ID
          </span>
          <h2 className="text-lg font-bold text-gray-800">
            System ID & Username Numbering Formats
          </h2>
        </div>
        <p className="mt-1 text-xs text-gray-500">
          Configure how Student, Teacher, and Parent accounts are assigned primary usernames and
          unique identity codes.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="flex flex-col gap-6">
        {/* STUDENT ID FORMAT */}
        <div className="flex flex-col gap-3 rounded-xl border border-blue-100 bg-blue-50/30 p-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div>
              <span className="text-sm font-semibold text-blue-900">Student ID Configuration</span>
              <p className="text-xs text-gray-500">Autogenerated when admitting new students</p>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-gray-500">Next Sample ID:</span>
              <span className="rounded-lg bg-blue-600 px-3 py-1 font-mono text-xs font-bold text-white shadow-sm">
                {studentPreview}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-4 pt-1 sm:grid-cols-2 lg:grid-cols-4">
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-semibold text-gray-600">Prefix</label>
              <input
                type="text"
                value={studentPrefix}
                onChange={(e) => {
                  const prefix = e.target.value.toUpperCase();
                  setStudentPrefix(prefix);
                  setStudentFormat(`${prefix}[YYYY][SEQ]`);
                }}
                className="rounded-lg border border-gray-200 bg-white p-2 font-mono text-xs uppercase shadow-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                maxLength={8}
              />
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-semibold text-gray-600">Sequence Digits</label>
              <select
                value={studentDigits}
                onChange={(e) => setStudentDigits(Number(e.target.value))}
                className="rounded-lg border border-gray-200 bg-white p-2 text-xs shadow-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
              >
                <option value={3}>3 Digits (001)</option>
                <option value={4}>4 Digits (0001)</option>
                <option value={5}>5 Digits (00001)</option>
                <option value={6}>6 Digits (000001)</option>
              </select>
            </div>

            <div className="flex flex-col gap-1.5 lg:col-span-2">
              <label className="text-xs font-semibold text-gray-600">
                Format Template{" "}
                <span className="text-[10px] text-gray-400">([PREFIX], [YYYY], [SEQ])</span>
              </label>
              <input
                type="text"
                value={studentFormat}
                onChange={(e) => setStudentFormat(e.target.value)}
                className="rounded-lg border border-gray-200 bg-white p-2 font-mono text-xs shadow-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                placeholder="STU[YYYY][SEQ]"
              />
            </div>
          </div>
        </div>

        {/* TEACHER ID FORMAT */}
        <div className="flex flex-col gap-3 rounded-xl border border-purple-100 bg-purple-50/30 p-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div>
              <span className="text-sm font-semibold text-purple-900">
                Teacher ID Configuration
              </span>
              <p className="text-xs text-gray-500">Autogenerated when onboarding faculty</p>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-gray-500">Next Sample ID:</span>
              <span className="rounded-lg bg-purple-600 px-3 py-1 font-mono text-xs font-bold text-white shadow-sm">
                {teacherPreview}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-4 pt-1 sm:grid-cols-2 lg:grid-cols-4">
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-semibold text-gray-600">Prefix</label>
              <input
                type="text"
                value={teacherPrefix}
                onChange={(e) => {
                  const prefix = e.target.value.toUpperCase();
                  setTeacherPrefix(prefix);
                  setTeacherFormat(`${prefix}[YYYY][SEQ]`);
                }}
                className="rounded-lg border border-gray-200 bg-white p-2 font-mono text-xs uppercase shadow-sm outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-500"
                maxLength={8}
              />
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-semibold text-gray-600">Sequence Digits</label>
              <select
                value={teacherDigits}
                onChange={(e) => setTeacherDigits(Number(e.target.value))}
                className="rounded-lg border border-gray-200 bg-white p-2 text-xs shadow-sm outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-500"
              >
                <option value={3}>3 Digits (001)</option>
                <option value={4}>4 Digits (0001)</option>
                <option value={5}>5 Digits (00001)</option>
              </select>
            </div>

            <div className="flex flex-col gap-1.5 lg:col-span-2">
              <label className="text-xs font-semibold text-gray-600">
                Format Template{" "}
                <span className="text-[10px] text-gray-400">([PREFIX], [YYYY], [SEQ])</span>
              </label>
              <input
                type="text"
                value={teacherFormat}
                onChange={(e) => setTeacherFormat(e.target.value)}
                className="rounded-lg border border-gray-200 bg-white p-2 font-mono text-xs shadow-sm outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-500"
                placeholder="TCH[YYYY][SEQ]"
              />
            </div>
          </div>
        </div>

        {/* PARENT ID FORMAT */}
        <div className="flex flex-col gap-3 rounded-xl border border-amber-100 bg-amber-50/30 p-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div>
              <span className="text-sm font-semibold text-amber-900">
                Parent / Guardian ID Configuration
              </span>
              <p className="text-xs text-gray-500">
                Primary login uses 10-digit Phone Number; system fallback prefix configured below.
              </p>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-gray-500">Next Sample ID:</span>
              <span className="rounded-lg bg-amber-600 px-3 py-1 font-mono text-xs font-bold text-white shadow-sm">
                {parentPreview}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-4 pt-1 sm:grid-cols-2 lg:grid-cols-4">
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-semibold text-gray-600">Prefix</label>
              <input
                type="text"
                value={parentPrefix}
                onChange={(e) => {
                  const prefix = e.target.value.toUpperCase();
                  setParentPrefix(prefix);
                  setParentFormat(`${prefix}[SEQ]`);
                }}
                className="rounded-lg border border-gray-200 bg-white p-2 font-mono text-xs uppercase shadow-sm outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500"
                maxLength={8}
              />
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-semibold text-gray-600">Sequence Digits</label>
              <select
                value={parentDigits}
                onChange={(e) => setParentDigits(Number(e.target.value))}
                className="rounded-lg border border-gray-200 bg-white p-2 text-xs shadow-sm outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500"
              >
                <option value={3}>3 Digits (001)</option>
                <option value={4}>4 Digits (0001)</option>
                <option value={5}>5 Digits (00001)</option>
              </select>
            </div>

            <div className="flex flex-col gap-1.5 lg:col-span-2">
              <label className="text-xs font-semibold text-gray-600">Format Template</label>
              <input
                type="text"
                value={parentFormat}
                onChange={(e) => setParentFormat(e.target.value)}
                className="rounded-lg border border-gray-200 bg-white p-2 font-mono text-xs shadow-sm outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500"
                placeholder="PRN[SEQ]"
              />
            </div>
          </div>
        </div>

        <button
          type="submit"
          className="self-end rounded-xl bg-blue-600 px-6 py-2.5 text-xs font-semibold text-white shadow transition hover:bg-blue-700 active:scale-[0.99]"
        >
          Save ID Numbering Configurations
        </button>
      </form>
    </div>
  );
}
